version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
    - 80:8000
    env_file: .env
    depends_on:
      - storage
    entrypoint:
      - scripts/docker-entrypoint.sh

  storage:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${BD_NAME}
      MYSQL_USER: ${BD_USER}
      MYSQL_PASSWORD: ${BD_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${BD_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - dbdata:/var/lib/mysql
