version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
    - 80:8000
    env_file:
      - .env
    depends_on:
      - storage
    entrypoint:
      - scripts/docker-entrypoint.sh
