# Generated by Django 2.2.9 on 2020-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
